### ISSUE TITLE
Parts list

### ISSUE THREAD

**Issue by edef1c** [jaseg/openmind-first-protoype#1]
I want to build a few of these, but I don't see a clear parts list. Care to share?

**Comment by jaseg** [comment]
I just exported one with eagle and committed it. The two voltage regulators and the op-amp are not critical (you should be able to exchange them with any similar parts). It should also be possible to use other microcontrollers (e.g. an ATMega328 instead of the ATMega8).
Please note that I improved upon this stuff and made a new version which is available at https://github.com/jaseg/OpenMind-micro
